line-length = 90
target-version = "py310"

[lint]
select = ["E", "F", "I", "B", "UP", "SIM", "RUF"]

ignore = [
    "B008",
    "E501",
    "RUF001",
    "SIM103",
]

[lint.per-file-ignores]
"tests/*" = ["E402"]
